CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name     VARCHAR(255) NOT NULL,
                       email         VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       role          VARCHAR(20)  NOT NULL,
                       created_at    TIMESTAMP    NOT NULL,

                       CONSTRAINT uq_users_email UNIQUE (email),
                       CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'DOCTOR', 'PATIENT'))
);

-- no separate index needed: the UNIQUE constraint above already creates one on email

CREATE TABLE doctor_profiles (
                                 id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id           BIGINT         NOT NULL,
                                 specialization    VARCHAR(255)   NOT NULL,
                                 qualifications    VARCHAR(255),
                                 bio               VARCHAR(255),
                                 consultation_fee  NUMERIC(19, 2) NOT NULL,

                                 CONSTRAINT uq_doctor_profiles_user_id UNIQUE (user_id),
                                 CONSTRAINT fk_doctor_profiles_user
                                     FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Note: findBySpecializationContainingIgnoreCase does a leading-wildcard LIKE ('%term%'),
-- which a plain B-tree index can't accelerate. This index only helps exact/prefix lookups.
-- If specialization search gets slow at scale, switch to a pg_trgm GIN index instead:
--    CREATE EXTENSION IF NOT EXISTS pg_trgm;
--    CREATE INDEX idx_doctor_profiles_specialization_trgm ON doctor_profiles USING gin (specialization gin_trgm_ops);
CREATE INDEX idx_doctor_profiles_specialization ON doctor_profiles (LOWER(specialization));

CREATE TABLE availability_slots (
                                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    doctor_id  BIGINT    NOT NULL,
                                    start_time TIMESTAMP NOT NULL,
                                    end_time   TIMESTAMP NOT NULL,
                                    is_booked  BOOLEAN   NOT NULL DEFAULT FALSE,
                                    version    BIGINT,

                                    CONSTRAINT fk_availability_slots_doctor
                                        FOREIGN KEY (doctor_id) REFERENCES doctor_profiles (id),
                                    CONSTRAINT chk_availability_slots_time_order
                                        CHECK (end_time > start_time)
);

-- speeds up AvailabilitySlotRepository.findByDoctorProfile_IdAndIsBookedFalseAndStartTimeBetween
CREATE INDEX idx_availability_slots_doctor_booked_start
    ON availability_slots (doctor_id, is_booked, start_time);

CREATE TABLE appointments (
                              id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id BIGINT      NOT NULL,
                              slot_id    BIGINT      NOT NULL,
                              status     VARCHAR(20) NOT NULL,
                              reason     TEXT,
                              created_at TIMESTAMP   NOT NULL,

                              CONSTRAINT uq_appointments_slot_id UNIQUE (slot_id),
                              CONSTRAINT fk_appointments_patient
                                  FOREIGN KEY (patient_id) REFERENCES users (id),
                              CONSTRAINT fk_appointments_slot
                                  FOREIGN KEY (slot_id) REFERENCES availability_slots (id),
                              CONSTRAINT chk_appointments_status
                                  CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'))
);

-- speeds up AppointmentRepository.findByPatientId
CREATE INDEX idx_appointments_patient_id ON appointments (patient_id);

-- speeds up AppointmentRepository.findByStatus
CREATE INDEX idx_appointments_status ON appointments (status);