-- Email verification: existing accounts start unverified. Enforcement is controlled by
-- app.email.verification-required, so flipping the flag on makes existing users verify once.
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Only a SHA-256 hash of each token is stored; the raw token exists only in the emailed link.
CREATE TABLE email_verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    used_at    TIMESTAMP,
    created_at TIMESTAMP   NOT NULL,

    CONSTRAINT uq_email_verification_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_email_verification_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens (user_id);

-- Profile photos live in their own table so listing doctors never loads image bytes.
-- Stored images are re-encoded server-side (512x512 JPEG), typically 30-80 KB each.
CREATE TABLE profile_photos (
    user_id      BIGINT      PRIMARY KEY,
    content_type VARCHAR(50) NOT NULL,
    data         BYTEA       NOT NULL,
    updated_at   TIMESTAMP   NOT NULL,

    CONSTRAINT fk_profile_photos_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Cache-busting version for the photo URL; NULL means the doctor has no photo.
ALTER TABLE doctor_profiles ADD COLUMN photo_version BIGINT;
