-- Workplace locations for doctors. A doctor can work at several places; at most one is primary.
-- Written to be re-runnable: every statement tolerates objects that already exist.
CREATE TABLE IF NOT EXISTS practice_locations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id     BIGINT        NOT NULL,
    facility_name VARCHAR(150)  NOT NULL,
    address_line1 VARCHAR(200)  NOT NULL,
    address_line2 VARCHAR(200),
    city          VARCHAR(100)  NOT NULL,
    state_region  VARCHAR(100),
    postal_code   VARCHAR(20),
    country       VARCHAR(2)    NOT NULL,           -- ISO 3166-1 alpha-2, upper-case
    latitude      NUMERIC(9, 6),                    -- optional; both or neither
    longitude     NUMERIC(9, 6),
    is_primary    BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL,

    CONSTRAINT fk_practice_locations_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT chk_practice_locations_country CHECK (country ~ '^[A-Z]{2}$'),
    CONSTRAINT chk_practice_locations_coords
        CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CONSTRAINT chk_practice_locations_lat CHECK (latitude  BETWEEN -90  AND 90),
    CONSTRAINT chk_practice_locations_lng CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_practice_locations_doctor_id ON practice_locations (doctor_id);
CREATE INDEX IF NOT EXISTS idx_practice_locations_city ON practice_locations (LOWER(city));

-- At most one primary location per doctor.
CREATE UNIQUE INDEX IF NOT EXISTS uq_practice_locations_one_primary
    ON practice_locations (doctor_id) WHERE is_primary;
